version: "3.5"

services:
  db:
    container_name: db
    image: 'postgres'
    networks:
      - proxy_net
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
    # volumes:
    #   - /home/le1ouch/workspace/sonarqube/postgres/:/var/lib/postgresql
    #   - /home/le1ouch/workspace/sonarqube/postgres/:/var/lib/postgresql/data

  sonarqube_container:
    container_name: sonarqube_container
    depends_on:
      - db
    image: sonarqube
    networks:
      - proxy_net
    restart: always
    expose:
      - "9000"
    env_file:
      - sonarqube.env
    volumes:
      - /home/le1ouch/workspace/sonarqube/sonarqube_container/:/opt/sonarqube/conf
      - /home/le1ouch/workspace/sonarqube/sonarqube_container/:/opt/sonarqube/data
      - /home/le1ouch/workspace/sonarqube/sonarqube_container/:/opt/sonarqube/extensions
      - /home/le1ouch/workspace/sonarqube/sonarqube_container/:/opt/sonarqube/lib/bundled-plugins
      - /home/le1ouch/workspace/sonarqube/sonarqube_container/logs/:/opt/sonarqube/logs

  reverse_proxy:
    container_name: reverse_proxy
    depends_on:
      - sonarqube_container
    image: nginx
    networks:
      - proxy_net
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /home/le1ouch/workspace/sonarqube/default.conf:/etc/nginx/conf.d/default.conf
      - /home/le1ouch/workspace/sonarqube/sonarqube.crt:/etc/ssl/certs/sonarqube.crt
      - /home/le1ouch/workspace/sonarqube/sonarqube.key:/etc/ssl/private/sonarqube.key

networks:
  proxy_net: